name: skull_maze
description: "Skull Maze Project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.16.0
  flame_audio: ^2.1.0
  provider: ^6.1.1
  sensors_plus: ^6.1.0
  
  # Firebase Core & Analytics
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.0
  
  # Firebase Auth & Database
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.0.0
  firebase_storage: ^12.0.0 # Added for storing user uploaded images
  
  # Social Auth
  google_sign_in: ^6.2.1

  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  
  # Persistencia de preferencias
  shared_preferences: ^2.2.2
  
  # Base de datos local
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Notificaciones y Vibraci√≥n
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  vibration: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # AUDIO
    - assets/audio/level.mp3
    - assets/audio/menu.mp3
    - assets/audio/notification.mp3
    # IMAGES
    - assets/images/Personajes/Catty.png
    - assets/images/Personajes/Doggy.png
    - assets/images/Personajes/Robo.png
    - assets/images/Personajes/Setty.png
    - assets/images/Personajes/Snoopy.png
    - assets/images/Personajes/Sora.jpeg
    - assets/images/Personajes/Special Hallowen.png
    - assets/images/Personajes/Ury.jpeg
    # APP
    - assets/images/App/Logo.png
